#!/usr/bin/perl

warn "foo";
my $x;

for (1..2) { 
    {
        my $x;
    }
}

while (1) {
    my $y;
}

for (1; 1; 1) { my $x; }

do { my $x } for 1..10;

grep { my $x } 1..4;
grep my $x, 1..5;
map { my $x } 1..4;
sort { my $x; $x++; } 1, 2, my $z;
s/f/my $x/e;

for (sub {my $p }, sub { my $q }) {
    1;
}

while (sub {my $r }) { 1; }

=begin Loop ops

Any child of
    leaveloop
    substcont

Second child of
    grepstart
    mapstart
    sort
